[platformio]
default_envs = esp32D
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_unflags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  +<wilde_timer_firmware/>

[env:esp32D]
board = esp32dev
build_src_filter =
  +<wilde_timer_firmware/>
